//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMvaderGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RAMvaderGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        public static string btAttach {
            get {
                return ResourceManager.GetString("btAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btClear {
            get {
                return ResourceManager.GetString("btClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        public static string btDetach {
            get {
                return ResourceManager.GetString("btDetach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK!.
        /// </summary>
        public static string btOk {
            get {
                return ResourceManager.GetString("btOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh now!.
        /// </summary>
        public static string btRefresh {
            get {
                return ResourceManager.GetString("btRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically refresh?.
        /// </summary>
        public static string chkAutomaticRefresh {
            get {
                return ResourceManager.GetString("chkAutomaticRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze value?.
        /// </summary>
        public static string chkFreezeValueQuestion {
            get {
                return ResourceManager.GetString("chkFreezeValueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string colAddress {
            get {
                return ResourceManager.GetString("colAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze?.
        /// </summary>
        public static string colFreeze {
            get {
                return ResourceManager.GetString("colFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string colIdentifier {
            get {
                return ResourceManager.GetString("colIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string colType {
            get {
                return ResourceManager.GetString("colType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string colValue {
            get {
                return ResourceManager.GetString("colValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses:.
        /// </summary>
        public static string lblAddressesPrompt {
            get {
                return ResourceManager.GetString("lblAddressesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string lblAddressPrompt {
            get {
                return ResourceManager.GetString("lblAddressPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONSOLE.
        /// </summary>
        public static string lblConsole {
            get {
                return ResourceManager.GetString("lblConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string lblDescriptionPrompt {
            get {
                return ResourceManager.GetString("lblDescriptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target process&apos; endianness:.
        /// </summary>
        public static string lblProcessEndianness {
            get {
                return ResourceManager.GetString("lblProcessEndianness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string lblProcesses {
            get {
                return ResourceManager.GetString("lblProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target process&apos; pointer size:.
        /// </summary>
        public static string lblProcessPointerSize {
            get {
                return ResourceManager.GetString("lblProcessPointerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, paste all addresses of the variables of the RAMvaderTarget application in the order they appear when you type the &quot;print&quot; command in that program (starting from Byte and ending in Double).
        ///Addresses should be separated by new lines..
        /// </summary>
        public static string lblRAMvaderTestTargetAddInstructions {
            get {
                return ResourceManager.GetString("lblRAMvaderTestTargetAddInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time (ms).
        /// </summary>
        public static string lblRefreshTime {
            get {
                return ResourceManager.GetString("lblRefreshTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string lblTypeByte {
            get {
                return ResourceManager.GetString("lblTypeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        public static string lblTypeDouble {
            get {
                return ResourceManager.GetString("lblTypeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int32.
        /// </summary>
        public static string lblTypeInt32 {
            get {
                return ResourceManager.GetString("lblTypeInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int64.
        /// </summary>
        public static string lblTypeInt64 {
            get {
                return ResourceManager.GetString("lblTypeInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntPtr.
        /// </summary>
        public static string lblTypeIntPtr {
            get {
                return ResourceManager.GetString("lblTypeIntPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string lblTypePrompt {
            get {
                return ResourceManager.GetString("lblTypePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string lblTypeSingle {
            get {
                return ResourceManager.GetString("lblTypeSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt16.
        /// </summary>
        public static string lblTypeUint16 {
            get {
                return ResourceManager.GetString("lblTypeUint16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt64.
        /// </summary>
        public static string lblTypeUint64 {
            get {
                return ResourceManager.GetString("lblTypeUint64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UInt64.
        /// </summary>
        public static string lblTypeUint642 {
            get {
                return ResourceManager.GetString("lblTypeUint642", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string lblValuePrompt {
            get {
                return ResourceManager.GetString("lblValuePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string mnuAddAddress {
            get {
                return ResourceManager.GetString("mnuAddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected address.
        /// </summary>
        public static string mnuDeleteAddress {
            get {
                return ResourceManager.GetString("mnuDeleteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RAMvaderTestTarget addresses.
        /// </summary>
        public static string mnuRAMvaderTestTargetAdd {
            get {
                return ResourceManager.GetString("mnuRAMvaderTestTargetAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze using predefined test values.
        /// </summary>
        public static string mnuRAMvaderTestTargetFreeze {
            get {
                return ResourceManager.GetString("mnuRAMvaderTestTargetFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvaderTestTarget.
        /// </summary>
        public static string mnuRAMvaderTestTargetOptions {
            get {
                return ResourceManager.GetString("mnuRAMvaderTestTargetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has started..
        /// </summary>
        public static string strConsoleMsgAppStarted {
            get {
                return ResourceManager.GetString("strConsoleMsgAppStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached to process &quot;{0}&quot; (PID = {1})..
        /// </summary>
        public static string strConsoleMsgAttachedToProcess {
            get {
                return ResourceManager.GetString("strConsoleMsgAttachedToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic refreshment of the list of registered addresses has been turned off..
        /// </summary>
        public static string strConsoleMsgAutomaticRefreshmentOff {
            get {
                return ResourceManager.GetString("strConsoleMsgAutomaticRefreshmentOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically refreshing the list of registered addresses..
        /// </summary>
        public static string strConsoleMsgAutomaticRefreshmentOn {
            get {
                return ResourceManager.GetString("strConsoleMsgAutomaticRefreshmentOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted selected entry(ies)..
        /// </summary>
        public static string strConsoleMsgDeletedEntries {
            get {
                return ResourceManager.GetString("strConsoleMsgDeletedEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detached from process &quot;{0}&quot; (PID = {1})..
        /// </summary>
        public static string strConsoleMsgDetachedFromProcess {
            get {
                return ResourceManager.GetString("strConsoleMsgDetachedFromProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually refreshed addresses list..
        /// </summary>
        public static string strConsoleMsgManualRefreshment {
            get {
                return ResourceManager.GetString("strConsoleMsgManualRefreshment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes list updated ({0} processes found)..
        /// </summary>
        public static string strConsoleMsgProcessesListUpdated {
            get {
                return ResourceManager.GetString("strConsoleMsgProcessesListUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvaderTestTarget addresses have been successfully added..
        /// </summary>
        public static string strConsoleMsgRAMvaderTestTargetAddressesAdded {
            get {
                return ResourceManager.GetString("strConsoleMsgRAMvaderTestTargetAddressesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvaderTestTarget addresses have frozen with test values..
        /// </summary>
        public static string strConsoleMsgRAMvaderTestTargetAddressesFrozen {
            get {
                return ResourceManager.GetString("strConsoleMsgRAMvaderTestTargetAddressesFrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered a new (empty) entry..
        /// </summary>
        public static string strConsoleMsgRegisteredNewEntry {
            get {
                return ResourceManager.GetString("strConsoleMsgRegisteredNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write the value to the target process&apos; memory space!.
        /// </summary>
        public static string strErrorCannotUpdateValueMsg {
            get {
                return ResourceManager.GetString("strErrorCannotUpdateValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update value!.
        /// </summary>
        public static string strErrorCannotUpdateValueTitle {
            get {
                return ResourceManager.GetString("strErrorCannotUpdateValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach to the specified process!
        ///Please, refresh and verify if the process is still running..
        /// </summary>
        public static string strErrorDuringAttachmentMsg {
            get {
                return ResourceManager.GetString("strErrorDuringAttachmentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to attach!.
        /// </summary>
        public static string strErrorDuringAttachmentTitle {
            get {
                return ResourceManager.GetString("strErrorDuringAttachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detach from the target process!
        ///It is recommended to restart the application..
        /// </summary>
        public static string strErrorDuringDetachmentMsg {
            get {
                return ResourceManager.GetString("strErrorDuringDetachmentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detach!.
        /// </summary>
        public static string strErrorDuringDetachmentTitle {
            get {
                return ResourceManager.GetString("strErrorDuringDetachmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input value is invalid for this data type!
        ///Please, check if the value is well formatted and if it obeys the limits of the data type of the registered address..
        /// </summary>
        public static string strErrorInvalidInputValueMsg {
            get {
                return ResourceManager.GetString("strErrorInvalidInputValueMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input!.
        /// </summary>
        public static string strErrorInvalidInputValueTitle {
            get {
                return ResourceManager.GetString("strErrorInvalidInputValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed input!.
        /// </summary>
        public static string strErrorMalformedInput {
            get {
                return ResourceManager.GetString("strErrorMalformedInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of registered address entries ({0}) is different from the expected number of entries ({1})!
        ///
        ///Please, right click the grid of registered addresses and go to:
        ///RAMvaderTestTarget &gt; Add RAMvaderTestTarget addresses
        ///
        ///There, you can add the test addresses in the right order..
        /// </summary>
        public static string strErrorRAMvaderTestTargetFreezeCountUnmatchedMsg {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetFreezeCountUnmatchedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong number of registered addresses.
        /// </summary>
        public static string strErrorRAMvaderTestTargetFreezeCountUnmatchedTitle {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetFreezeCountUnmatchedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the registered address entry with index {0} identified by &quot;{1}&quot; is {2}, while it was expected to be of type {3}!.
        /// </summary>
        public static string strErrorRAMvaderTestTargetFreezeTypesUnmatchedMsg {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetFreezeTypesUnmatchedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong type of entry.
        /// </summary>
        public static string strErrorRAMvaderTestTargetFreezeTypesUnmatchedTitle {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetFreezeTypesUnmatchedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} is not an hexadecimal address: {1}..
        /// </summary>
        public static string strErrorRAMvaderTestTargetInvalidLine {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetInvalidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must copy {0} addresses from RAMvaderTestTarget application for this utility to work!
        ///{1} addresses were copied from the application..
        /// </summary>
        public static string strErrorRAMvaderTestTargetNotEnoughLinesInInputMsg {
            get {
                return ResourceManager.GetString("strErrorRAMvaderTestTargetNotEnoughLinesInInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed.
        /// </summary>
        public static string strNewAddressId {
            get {
                return ResourceManager.GetString("strNewAddressId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type something to filter the list..
        /// </summary>
        public static string strToolTipTypeToFilter {
            get {
                return ResourceManager.GetString("strToolTipTypeToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit address.
        /// </summary>
        public static string wndTitleEditAddress {
            get {
                return ResourceManager.GetString("wndTitleEditAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAMvader GUI.
        /// </summary>
        public static string wndTitleMainWindow {
            get {
                return ResourceManager.GetString("wndTitleMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RAMvaderTestTarget addresses.
        /// </summary>
        public static string wndTitleRAMvaderTestTargetAdd {
            get {
                return ResourceManager.GetString("wndTitleRAMvaderTestTargetAdd", resourceCulture);
            }
        }
    }
}
